# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: smarthome.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='smarthome.proto',
  package='smart',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0fsmarthome.proto\x12\x05smart\"5\n\x06Packet\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06\x61\x63tion\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\x0c\"-\n\x0cListOfThings\x12\x1d\n\x06\x63oisas\x18\x01 \x03(\x0b\x32\r.smart.Things\"&\n\x06Things\x12\x0c\n\x04nome\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\tb\x06proto3')
)




_PACKET = _descriptor.Descriptor(
  name='Packet',
  full_name='smart.Packet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='smart.Packet.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='action', full_name='smart.Packet.action', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='content', full_name='smart.Packet.content', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=79,
)


_LISTOFTHINGS = _descriptor.Descriptor(
  name='ListOfThings',
  full_name='smart.ListOfThings',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='coisas', full_name='smart.ListOfThings.coisas', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=126,
)


_THINGS = _descriptor.Descriptor(
  name='Things',
  full_name='smart.Things',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nome', full_name='smart.Things.nome', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='smart.Things.status', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=128,
  serialized_end=166,
)

_LISTOFTHINGS.fields_by_name['coisas'].message_type = _THINGS
DESCRIPTOR.message_types_by_name['Packet'] = _PACKET
DESCRIPTOR.message_types_by_name['ListOfThings'] = _LISTOFTHINGS
DESCRIPTOR.message_types_by_name['Things'] = _THINGS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Packet = _reflection.GeneratedProtocolMessageType('Packet', (_message.Message,), {
  'DESCRIPTOR' : _PACKET,
  '__module__' : 'smarthome_pb2'
  # @@protoc_insertion_point(class_scope:smart.Packet)
  })
_sym_db.RegisterMessage(Packet)

ListOfThings = _reflection.GeneratedProtocolMessageType('ListOfThings', (_message.Message,), {
  'DESCRIPTOR' : _LISTOFTHINGS,
  '__module__' : 'smarthome_pb2'
  # @@protoc_insertion_point(class_scope:smart.ListOfThings)
  })
_sym_db.RegisterMessage(ListOfThings)

Things = _reflection.GeneratedProtocolMessageType('Things', (_message.Message,), {
  'DESCRIPTOR' : _THINGS,
  '__module__' : 'smarthome_pb2'
  # @@protoc_insertion_point(class_scope:smart.Things)
  })
_sym_db.RegisterMessage(Things)


# @@protoc_insertion_point(module_scope)
